### ISSUE TITLE
Unable to locate geodistance_nodes.json file

### ISSUE THREAD

**Issue by gmuraleekrishna** [meera1hahn/Graph_LED#1]
Hello, 

I am trying to set up this repository as per the instructions in the INSTALL.md file. When I try to evaluate the model using 
`python run.py  --evaluate  --eval_ckpt ../../data/models/lingunet-skip.pt  --run_name lingunet-skip` I am getting the following error 

> Traceback (most recent call last):
>   File "run.py", line 261, in <module>
>     agent.run()
>   File "run.py", line 252, in run
>     self.run_train()
>   File "run.py", line 188, in run_train
>     loss, acc0m, acc5m = self.train_model()
>   File "run.py", line 145, in train_model
>     info_elem, texts, seq_lengths, target, maps, conversions, mode="train"
>   File "run.py", line 96, in run_epoch
>     args, preds.detach().cpu(), batch_conversions, info_elem, mode
>   File "/Graph_LED/src/utils.py", line 97, in distance_from_pixels
>     geodistance_nodes = json.load(open(args.geodistance_file))
> FileNotFoundError: [Errno 2] No such file or directory: '../../data/geodistance_nodes.json'

I tried
```
$ tree data/ --filelimit 9 -L 2
data/
├── base.pt
├── connectivity [92 entries exceeds filelimit, not opening dir]
├── distances [90 entries exceeds filelimit, not opening dir]
├── floorplans
│   ├── allScans_Node2pix.json
│   ├── floor_0
│   ├── floor_1
│   ├── floor_2
│   ├── floor_3
│   ├── floor_4
│   ├── pix2meshDistance.json
│   └── scan_levels.json
├── models
│   ├── crossmodal_att.pt
│   ├── crossmodal_simple.pt
│   └── lingunet-skip.pt
├── node_feats
│   └── 17DRP5sb8fy.pt
├── ResNet-152-places365.tsv
├── way_splits
│   ├── test_data.json
│   ├── train_data.json
│   ├── train_expanded_data.json
│   ├── valSeen_data.json
│   └── valUnseen_data.json
└── word_embeddings
    ├── glove_weights_matrix.npy
    ├── idx2word.json
    ├── w2v_weights_matrix.npy
    └── word2idx.json
```
It seems that the automated download script isn't downloading the  `geodistance_nodes.json` file. Where do I find it?

Thanks

**Comment by meera1hahn** [comment]
Hello,

You can find the file here: https://drive.google.com/file/d/18RcaK3rHDKPeouEvuxMUQ4a20yW-rF2U/view?usp=sharing

I will edit the download script to include this. Let me know if you have any other questions!

**Comment by meera1hahn** [comment]
You can find the file here: https://drive.google.com/file/d/18RcaK3rHDKPeouEvuxMUQ4a20yW-rF2U/view?usp=sharing

the download script now includes this
