### ISSUE TITLE
Mapping navigation paths with Matterport3D scenes

### ISSUE THREAD

**Issue by nilinykh** [meera1hahn/Graph_LED#2]
Thank you for your amazing work and this dataset!

I was wondering if there is a straightforward way to map navigation of the Observed with visual observations in the Matterport3D dataset. Basically, I would like to extract the sequence of visual scenes which were visible to the Observer during the dialogue. Did you record the navigation episodes or you only kept the path coordinates that the Observer followed?
I have a guess that I need to use `viewpoint ids`, which can be mapped with `[viewpoint, pixel location, floor]` information, but then this would give me navigation trajectory only, right? As in Figure 4, second example in the paper. Would this information be enough to map navigation paths with M3D scenes?

Also, did you use Habitat-Sim to place the Observer in M3D environment?

**Comment by meera1hahn** [comment]
Hi, 

Thanks for your interest in the dataset. 


* The dataset was collected using the [Mp3d simulator](https://github.com/peteanderson80/Matterport3DSimulator). But you should be able to place the agents directly with the Habitat simulator for modeling and testing. 
    * Mapping the matterport viewpoints to habitat-sim coordinates would be the first place to start. Please find the mapping for each mp3d viewpoint id to the habitat coordinates [here](https://github.com/meera1hahn/Graph_LED/blob/main/scripts/mp3d_habitat_map.json) 
    * Once you have the habitat points for the viewpoints, you can [set the agent](https://aihabitat.org/docs/habitat-sim/habitat_sim.agent.Agent.html#set_state) in using the habitat simulator 
    * You will probably need the headings then as I specify in the answer to the next question. So if you would like to use the habitat simulator over the matter port simulator let me know and I can retrieve the headings. 
    * Note that Matterport simulator is way point based aka the observer agent does not need to do local navigation in between nodes. You can simulate this in the habitat simulator using teleportation or using [shortest path follower](https://github.com/facebookresearch/habitat-lab/blob/master/examples/shortest_path_follower_example.py) function.
    * Overall I would recommend using the matterport simulator


* “Did you record the navigation episodes or you only kept the path coordinates that the Observer followed?” 
    * In the way split files for each episode there is a “detailedNavPath”. This is an array which has a list for each observer turn, containing the navigation path (in terms of viewpoints) for that turn. If there is only one viewpoint ID in that list for a turn, it means the observer did not navigate during that turn. 
    * This however doesn’t contain the heading of the observer. If you want to treat the viewpoints as 360 panos during modeling then you dont need the heading. Otherwise if you want and agent with a limited field of view I can grab the headings and send them to you (we did record these).

**Comment by meera1hahn** [comment]
Also please find the mapping for each mp3d viewpoint id to the habitat coordinates [here](https://github.com/meera1hahn/Graph_LED/blob/main/scripts/mp3d_habitat_map.json)
